import os

SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
APP_SECRET_KEY = os.getenv("APP_SECRET_KEY")
UPLOAD_BUCKET = os.getenv("UPLOAD_BUCKET")
UPLOAD_FOLDER = os.getenv("UPLOAD_FOLDER")
AWS_REGION = os.getenv("AWS_DEFAULT_REGION")
ENVIRONMENT = os.getenv("ENVIRONMENT")
IUGU_API_TOKEN = os.getenv("IUGU_API_TOKEN")
