version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ../data-volume:/var/lib/postgresql/data
