version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - ../data-volume:/var/lib/postgresql/data
