"""Add pix_discount itinerary and itinerary_rule table

Revision ID: 207fb6200163
Revises: e061e3fa6040
Create Date: 2024-01-31 19:52:48.068086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207fb6200163'
down_revision = 'e061e3fa6040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_discount', sa.Numeric(), server_default='0', nullable=False))

    with op.batch_alter_table('itinerary_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_discount', sa.Numeric(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('seat_price', sa.Numeric(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('montly_interest', sa.Numeric(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_rule', schema=None) as batch_op:
        batch_op.drop_column('montly_interest')
        batch_op.drop_column('seat_price')
        batch_op.drop_column('pix_discount')

    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('pix_discount')

    # ### end Alembic commands ###
