"""Booking and BookingTraveler model creation

Revision ID: 2e0cb07ebf53
Revises: ea8fc66fb249
Create Date: 2024-01-27 13:36:03.756143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0cb07ebf53'
down_revision = 'ea8fc66fb249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('payer_name', sa.String(), nullable=False),
    sa.Column('payer_email', sa.String(), nullable=False),
    sa.Column('payer_phone', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_traveler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('traveler_name', sa.String(), nullable=False),
    sa.Column('traveler_birthdate', sa.Date(), nullable=False),
    sa.Column('traveler_gender', sa.String(), nullable=False),
    sa.Column('traveler_extras', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_traveler')
    op.drop_table('booking')
    # ### end Alembic commands ###
