"""add total_items_cents, discount_cents and invoice_extras on invoices table

Revision ID: 4d1584124c82
Revises: 3f7fa8815a44
Create Date: 2024-02-29 20:28:37.120511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1584124c82'
down_revision = '3f7fa8815a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_total_cents', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('discount_cents', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('invoice_extras', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_extras')
        batch_op.drop_column('discount_cents')
        batch_op.drop_column('items_total_cents')

    # ### end Alembic commands ###
