"""add total_cents into booking_travelers table

Revision ID: 0d1e696c1c0c
Revises: c50d819e7432
Create Date: 2024-02-11 08:54:21.028961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1e696c1c0c'
down_revision = 'c50d819e7432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_traveler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cents', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_traveler', schema=None) as batch_op:
        batch_op.drop_column('total_cents')

    # ### end Alembic commands ###
