"""add rank on institution table

Revision ID: 3f7fa8815a44
Revises: d62b8e1d7d33
Create Date: 2024-02-20 11:53:59.575827

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f7fa8815a44"
down_revision = "d62b8e1d7d33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("institution", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ranking", sa.Numeric(), server_default="9999", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("institution", schema=None) as batch_op:
        batch_op.drop_column("ranking")

    # ### end Alembic commands ###
