"""add cover_small on itinerary table

Revision ID: d62b8e1d7d33
Revises: 0d1e696c1c0c
Create Date: 2024-02-16 08:47:31.323928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62b8e1d7d33'
down_revision = '0d1e696c1c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_small_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'file', ['cover_small_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_small_id')

    # ### end Alembic commands ###
