"""Drop payment rule fields from itinerary table

Revision ID: dd05ed4bdc8f
Revises: 207fb6200163
Create Date: 2024-01-31 22:53:26.431977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd05ed4bdc8f'
down_revision = '207fb6200163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('purchase_deadline')
        batch_op.drop_column('seat_price')
        batch_op.drop_column('pix_discount')
        batch_op.drop_column('installments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installments', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pix_discount', sa.NUMERIC(), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seat_price', sa.NUMERIC(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('purchase_deadline', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
